# Generated by Django 5.1.2 on 2024-11-14 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_farmerprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FarmerProfile',
        ),
    ]
