# Generated by Django 5.1.2 on 2024-11-14 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_delete_farmerprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanapplication',
            name='loan_amount',
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='loan_pdf',
            field=models.FileField(blank=True, null=True, upload_to='loan_pdfs/'),
        ),
    ]
