# Generated by Django 5.1.2 on 2024-11-15 14:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_loanapplication_loan_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanApplicationCooperative',
            fields=[
                ('loan_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('loan_status', models.CharField(default='Pending', max_length=20)),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('loan_pdf', models.FileField(blank=True, null=True, upload_to='loan_pdfs/')),
                ('cooperative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cooperative')),
                ('financial_institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.financialinstitution')),
            ],
        ),
    ]
