# Generated by Django 5.1.2 on 2024-11-20 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_loanapplicationcooperative'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplication',
            name='loan_status',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='loanapplicationcooperative',
            name='loan_status',
            field=models.CharField(max_length=50),
        ),
    ]
