# Generated by Django 5.1.2 on 2024-11-22 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_loanapplication_loan_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplication',
            name='loan_status',
            field=models.CharField(default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='loanapplicationcooperative',
            name='loan_status',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
